channels.md
Неплохой канал с качественным видео, список технологий - длинный
=> Added TechnologiesWeb channel

channels.md
Ilya Kantor's channel has been added
=> Ilya Kantor's channel has been added

index.html
Меню-облако тэгов генерируется автоматически, нужные тэги просто классами указываеются. Например, class="JavaScript CSS"
=> HTML-страница с поиском по тэгам для GitHub Pages

channels.md
Убран повтор RubyScreencastsRu.
=> Убран повтор RubyScreencastsRu.

channels.md
Official YouTube channel for CSS-Tricks
=> added realcsstricks channel

ru.md
yandex front-end channel added
=> yandex front-end channel added

ru.md
TechnologiesWeb - Ruby, Javascript, SQL, хакинг, CMS
DeveloperStarter - курсы, лекции, и уроки по HTML, CSS, JavaScript, PHP, Java, Python, C++
The channels were banned and deleted.
=> The channels were banned and deleted

README.md
масса интересных туториалов по актуальным JS темам
=> Рекомендую канал 'The Net Ninja'

README.md
=> Add PenzaJS channel

README.md
- Added WebSchool and BrazilJS Weekly channel
- Added BrazilJS, FrontInPOA, FrontInSM and RSJS conference recordings playlist
=> Add Portuguese language channels section

README.md
Ukraine's smallest one conference's recordings.
=> Adding KyivJS youtube channel link

README.md
Ukraine's biggest conference recordings.
=> Adding OdessaJS youtube channel link

README.md
Added "Watch and Learn" channel that shows how to use Vue.js with Wordpress rest API and Drupal 8.
=> Added new channel to english category.

README.md
This channel has some 👌 stuff!
=> Add Ryan Christiani's channel

README.md
На трансляциях очень много полезного. На livecoding зачастую проводят уроки.
=> Add live coding streams

README.md
One of the Ukraine's biggest conference's recordings.
=> Adding LvivJS youtube channel link

README.md
Addition of several channels in Portuguese language.
=> Add Channels Portuguese Language

README.md
HighLoad++ - Профессиональная конференция разработчиков высоконагруженных систем
=> Add Habrahabr channel

README.md
https://www.youtube.com/watch?v=5LYrN_cAJoA&list=PL4cUxeGkcC9gQcYgjhBoeQH7wiAyZNrYa
=> edit add Vue

README.md
Added CodeWorkr youtube channel to English section; CodeWorkr teaches Javascript, Node.js and other related programming subjects
=> English youtube channels update

README.md
=> added SkillBranch-Russian Channel for Android, Design, Node.js+React

README.md
Following by https://github.com/andrew--r/frontend-case-studies/pull/1 :smiley:
=> Remove unnecessary "language" word from titles

README.md
=> Adding Coding with Dom

README.md
1. Fixed URL to Zaiste Programming youtube channel
2. Removed dead channels:
- George Mcknight
- Уроки веб-разработки
- .getInstance
=> Removed dead channels

README.md
I added Polish channels: Koduje, Samuraj Programowania, Hello Roman, Maciej Aniserowicz, overment, AlgoSmart - Marcin Czarkowski
=> Added some Polish channels

README.md
=> Added devmentorlive (JavaScript/React JS) and Kevin Powell (HTML, CSS, Layout/Design)
